package com.shinowit.dao.mapper;

import com.shinowit.entity.Teacher1;
import com.shinowit.entity.Teacher1Example;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface Teacher1Mapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher1
     *
     * @mbggenerated Wed Dec 24 19:23:50 CST 2014
     */
    int countByExample(Teacher1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher1
     *
     * @mbggenerated Wed Dec 24 19:23:50 CST 2014
     */
    int deleteByExample(Teacher1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher1
     *
     * @mbggenerated Wed Dec 24 19:23:50 CST 2014
     */
    int deleteByPrimaryKey(Integer teacherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher1
     *
     * @mbggenerated Wed Dec 24 19:23:50 CST 2014
     */
    int insert(Teacher1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher1
     *
     * @mbggenerated Wed Dec 24 19:23:50 CST 2014
     */
    int insertSelective(Teacher1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher1
     *
     * @mbggenerated Wed Dec 24 19:23:50 CST 2014
     */
    List<Teacher1> selectByExample(Teacher1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher1
     *
     * @mbggenerated Wed Dec 24 19:23:50 CST 2014
     */
    Teacher1 selectByPrimaryKey(Integer teacherId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher1
     *
     * @mbggenerated Wed Dec 24 19:23:50 CST 2014
     */
    int updateByExampleSelective(@Param("record") Teacher1 record, @Param("example") Teacher1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher1
     *
     * @mbggenerated Wed Dec 24 19:23:50 CST 2014
     */
    int updateByExample(@Param("record") Teacher1 record, @Param("example") Teacher1Example example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher1
     *
     * @mbggenerated Wed Dec 24 19:23:50 CST 2014
     */
    int updateByPrimaryKeySelective(Teacher1 record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher1
     *
     * @mbggenerated Wed Dec 24 19:23:50 CST 2014
     */
    int updateByPrimaryKey(Teacher1 record);

    List<Teacher1> selectPage(Teacher1Example example);

    Integer selectMaxPrimaryKeyValue();
}