package com.shinowit.entity;

import java.io.Serializable;
import java.util.List;

public class Teacher1 implements Serializable {

    private List<Student> studentList;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher1.teacher_id
     *
     * @mbggenerated Wed Dec 24 19:23:50 CST 2014
     */
    private Integer teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher1.name
     *
     * @mbggenerated Wed Dec 24 19:23:50 CST 2014
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table teacher1
     *
     * @mbggenerated Wed Dec 24 19:23:50 CST 2014
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher1.teacher_id
     *
     * @return the value of teacher1.teacher_id
     * @mbggenerated Wed Dec 24 19:23:50 CST 2014
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher1.teacher_id
     *
     * @param teacherId the value for teacher1.teacher_id
     * @mbggenerated Wed Dec 24 19:23:50 CST 2014
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher1.name
     *
     * @return the value of teacher1.name
     * @mbggenerated Wed Dec 24 19:23:50 CST 2014
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher1.name
     *
     * @param name the value for teacher1.name
     * @mbggenerated Wed Dec 24 19:23:50 CST 2014
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    public List<Student> getStudentList() {
        return studentList;
    }

    public void setStudentList(List<Student> studentList) {
        this.studentList = studentList;
    }
}